### ISSUE TITLE
这个sdk，玩呢？

### ISSUE THREAD

**Issue by feelingseas** [tencentyun/cos-cpp-sdk-v5#100]
浪费我好几天时间，也没解决。资料说明不够，项目依赖繁杂（我都怀疑是不是负责人自己都没搞明白？）多了我也不说了，我就说三点。
1
`// request 的构造函数中需要传入本地文件路径
    qcloud_cos::PutObjectByFileReq req(bucket_name, object_name, "/path/to/local/file");
    req.SetXCosStorageClass("STANDARD_IA")； // 调用 Set 方法设置元数据等
    qcloud_cos::PutObjectByFileResp resp;`
首页的上传示例，来个中文分号，你是怎么编译通过的（之前 也有人提到过一些低级错误）？
2
vs说用2017，别的版本呢？行还是不行。。怕是自己也没测试过吧。。
3
好多人遇到问题了，没有回复吧。。这才几个问题。。

想用qt集成，问题一堆。其他小伙伴们慎入！

好好好。你高冷。再见。

**Comment by Huberyxiao** [comment]
相关问题已处理或排期处理。有需求可通过腾讯云客服联系
