### ISSUE TITLE
注释中含有中文的情况下，中文和英文联合起来，吞掉了注释的*/，导致bug

### ISSUE THREAD

**Issue by shezhangjun** [tencentyun/cos-cpp-sdk-v5#102]
https://github.com/tencentyun/cos-cpp-sdk-v5/blob/master/include/response/object_resp.h#L652
这个文件，下载下来是UTF-8编码的，在用VS Code编译时会发生报错，如下图
C1071 在注释中遇到意外的文件结束 .\include\response\object_resp.h
![error](https://user-images.githubusercontent.com/50070809/158171968-0a4d6898-14c7-4413-b00b-1744ec98e2a0.png)

Line 652 /*批量及目录操作接口*/
这行如果转GB2132的话，会变成 /*鎵归噺鍙婄洰褰曟搷浣滄帴鍙?/ 
![error](https://user-images.githubusercontent.com/50070809/158171407-347e5dcf-b15b-423b-88ff-f40205bfd90e.png)
也就少了一个*/ 做注释终结器

这里如果改成 /*批量及目录操作接口 */ 再去转GB2132 就正常了
![success](https://user-images.githubusercontent.com/50070809/158171473-e360a399-9eff-4e14-822b-1de9ae707eef.png)

**Comment by Huberyxiao** [comment]
仅支持UTF8编译

**Comment by Huberyxiao** [comment]
当前问题已经修复哈
