### ISSUE TITLE
It not able to be compiled in ubuntu 20.04/22.04

### ISSUE THREAD

**Issue by qqsunkist** [tencentyun/cos-cpp-sdk-v5#107]
d /home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/build/src && /usr/bin/c++   -I/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/include -I/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include  -std=c++11 -Werror -Wall -Wextra   -o CMakeFiles/cossdk.dir/cos_api.cpp.o -c /home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/src/cos_api.cpp
In file included from /home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/include/op/bucket_op.h:15,
                 from /home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/include/cos_api.h:4,
                 from /home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/src/cos_api.cpp:1:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/include/response/bucket_resp.h: In member function ‘qcloud_cos::LoggingEnabled qcloud_cos::GetBucketLoggingResp::GetLoggingEnabled() const’:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/include/response/bucket_resp.h:343:53: error: implicitly-declared ‘qcloud_cos::LoggingEnabled::LoggingEnabled(const qcloud_cos::LoggingEnabled&)’ is deprecated [-Werror=deprecated-copy]
  343 |   LoggingEnabled GetLoggingEnabled() const { return m_rules; }
      |                                                     ^~~~~~~
In file included from /home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/include/cos_sys_config.h:5,
                 from /home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/include/op/bucket_op.h:10,
                 from /home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/include/cos_api.h:4,
                 from /home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/src/cos_api.cpp:1:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/include/cos_defines.h:516:19: note: because ‘qcloud_cos::LoggingEnabled’ has user-provided ‘qcloud_cos::LoggingEnabled& qcloud_cos::LoggingEnabled::operator=(const qcloud_cos::LoggingEnabled&)’
  516 |   LoggingEnabled& operator=(const LoggingEnabled& obj) {
      |                   ^~~~~~~~
In file included from /home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/Var.h:24,
                 from /home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/JSON/Array.h:23,
                 from /home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/JSON/Object.h:22,
                 from /home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/JSON/ParserImpl.h:22,
                 from /home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/JSON/Parser.h:22,
                 from /home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/include/cos_config.h:10,
                 from /home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/include/op/base_op.h:9,
                 from /home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/include/op/bucket_op.h:11,
                 from /home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/include/cos_api.h:4,
                 from /home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/src/cos_api.cpp:1:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = signed char; T = unsigned int]’:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:370:3:   required from ‘void Poco::Dynamic::VarHolder::convertSignedToUnsigned(const F&, T&) const [with F = signed char; T = unsigned int]’
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:771:36:   required from here
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const signed char’ and ‘unsigned int’ [-Werror=sign-compare]
  419 |   if (from > std::numeric_limits<T>::max())
      |       ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = signed char; T = long unsigned int]’:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:370:3:   required from ‘void Poco::Dynamic::VarHolder::convertSignedToUnsigned(const F&, T&) const [with F = signed char; T = long unsigned int]’
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:776:36:   required from here
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const signed char’ and ‘long unsigned int’ [-Werror=sign-compare]
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = signed char; T = long long unsigned int]’:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:370:3:   required from ‘void Poco::Dynamic::VarHolder::convertSignedToUnsigned(const F&, T&) const [with F = signed char; T = long long unsigned int]’
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:788:36:   required from here
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const signed char’ and ‘long long unsigned int’ [-Werror=sign-compare]
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = short int; T = unsigned int]’:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:370:3:   required from ‘void Poco::Dynamic::VarHolder::convertSignedToUnsigned(const F&, T&) const [with F = short int; T = unsigned int]’
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:927:36:   required from here
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const short int’ and ‘unsigned int’ [-Werror=sign-compare]
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = short int; T = long unsigned int]’:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:370:3:   required from ‘void Poco::Dynamic::VarHolder::convertSignedToUnsigned(const F&, T&) const [with F = short int; T = long unsigned int]’
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:932:36:   required from here
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const short int’ and ‘long unsigned int’ [-Werror=sign-compare]
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = short int; T = long long unsigned int]’:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:370:3:   required from ‘void Poco::Dynamic::VarHolder::convertSignedToUnsigned(const F&, T&) const [with F = short int; T = long long unsigned int]’
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:944:36:   required from here
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const short int’ and ‘long long unsigned int’ [-Werror=sign-compare]
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = int; T = unsigned int]’:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:370:3:   required from ‘void Poco::Dynamic::VarHolder::convertSignedToUnsigned(const F&, T&) const [with F = int; T = unsigned int]’
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:1081:36:   required from here
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const int’ and ‘unsigned int’ [-Werror=sign-compare]
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = int; T = long unsigned int]’:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:370:3:   required from ‘void Poco::Dynamic::VarHolder::convertSignedToUnsigned(const F&, T&) const [with F = int; T = long unsigned int]’
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:1086:36:   required from here
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const int’ and ‘long unsigned int’ [-Werror=sign-compare]
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = int; T = long long unsigned int]’:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:370:3:   required from ‘void Poco::Dynamic::VarHolder::convertSignedToUnsigned(const F&, T&) const [with F = int; T = long long unsigned int]’
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:1098:36:   required from here
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const int’ and ‘long long unsigned int’ [-Werror=sign-compare]
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = long int; T = long unsigned int]’:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:370:3:   required from ‘void Poco::Dynamic::VarHolder::convertSignedToUnsigned(const F&, T&) const [with F = long int; T = long unsigned int]’
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:1238:36:   required from here
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const long int’ and ‘long unsigned int’ [-Werror=sign-compare]
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = long int; T = long long unsigned int]’:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:370:3:   required from ‘void Poco::Dynamic::VarHolder::convertSignedToUnsigned(const F&, T&) const [with F = long int; T = long long unsigned int]’
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:1250:36:   required from here
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const long int’ and ‘long long unsigned int’ [-Werror=sign-compare]
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = unsigned int; T = signed char]’:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:405:3:   required from ‘void Poco::Dynamic::VarHolder::convertUnsignedToSigned(const F&, T&) const [with F = unsigned int; T = signed char]’
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:1674:36:   required from here
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const unsigned int’ and ‘signed char’ [-Werror=sign-compare]
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = unsigned int; T = short int]’:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:405:3:   required from ‘void Poco::Dynamic::VarHolder::convertUnsignedToSigned(const F&, T&) const [with F = unsigned int; T = short int]’
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:1679:36:   required from here
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const unsigned int’ and ‘short int’ [-Werror=sign-compare]
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = unsigned int; T = int]’:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:405:3:   required from ‘void Poco::Dynamic::VarHolder::convertUnsignedToSigned(const F&, T&) const [with F = unsigned int; T = int]’
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:1684:36:   required from here
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const unsigned int’ and ‘int’ [-Werror=sign-compare]
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = long unsigned int; T = signed char]’:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:405:3:   required from ‘void Poco::Dynamic::VarHolder::convertUnsignedToSigned(const F&, T&) const [with F = long unsigned int; T = signed char]’
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:1826:36:   required from here
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const long unsigned int’ and ‘signed char’ [-Werror=sign-compare]
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = long unsigned int; T = short int]’:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:405:3:   required from ‘void Poco::Dynamic::VarHolder::convertUnsignedToSigned(const F&, T&) const [with F = long unsigned int; T = short int]’
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:1831:36:   required from here
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const long unsigned int’ and ‘short int’ [-Werror=sign-compare]
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = long unsigned int; T = int]’:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:405:3:   required from ‘void Poco::Dynamic::VarHolder::convertUnsignedToSigned(const F&, T&) const [with F = long unsigned int; T = int]’
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:1836:36:   required from here
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const long unsigned int’ and ‘int’ [-Werror=sign-compare]
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = long unsigned int; T = long int]’:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:405:3:   required from ‘void Poco::Dynamic::VarHolder::convertUnsignedToSigned(const F&, T&) const [with F = long unsigned int; T = long int]’
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:1841:36:   required from here
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const long unsigned int’ and ‘long int’ [-Werror=sign-compare]
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = long unsigned int; T = long long int]’:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:405:3:   required from ‘void Poco::Dynamic::VarHolder::convertUnsignedToSigned(const F&, T&) const [with F = long unsigned int; T = long long int]’
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:1868:36:   required from here
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const long unsigned int’ and ‘long long int’ [-Werror=sign-compare]
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = long long int; T = long unsigned int]’:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:370:3:   required from ‘void Poco::Dynamic::VarHolder::convertSignedToUnsigned(const F&, T&) const [with F = long long int; T = long unsigned int]’
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:3322:36:   required from here
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const long long int’ and ‘long unsigned int’ [-Werror=sign-compare]
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = long long int; T = long long unsigned int]’:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:370:3:   required from ‘void Poco::Dynamic::VarHolder::convertSignedToUnsigned(const F&, T&) const [with F = long long int; T = long long unsigned int]’
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:3332:36:   required from here
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const long long int’ and ‘long long unsigned int’ [-Werror=sign-compare]
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = long long unsigned int; T = signed char]’:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:405:3:   required from ‘void Poco::Dynamic::VarHolder::convertUnsignedToSigned(const F&, T&) const [with F = long long unsigned int; T = signed char]’
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:3435:36:   required from here
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const long long unsigned int’ and ‘signed char’ [-Werror=sign-compare]
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = long long unsigned int; T = short int]’:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:405:3:   required from ‘void Poco::Dynamic::VarHolder::convertUnsignedToSigned(const F&, T&) const [with F = long long unsigned int; T = short int]’
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:3440:36:   required from here
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const long long unsigned int’ and ‘short int’ [-Werror=sign-compare]
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = long long unsigned int; T = int]’:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:405:3:   required from ‘void Poco::Dynamic::VarHolder::convertUnsignedToSigned(const F&, T&) const [with F = long long unsigned int; T = int]’
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:3445:36:   required from here
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const long long unsigned int’ and ‘int’ [-Werror=sign-compare]
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = long long unsigned int; T = long int]’:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:405:3:   required from ‘void Poco::Dynamic::VarHolder::convertUnsignedToSigned(const F&, T&) const [with F = long long unsigned int; T = long int]’
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:3450:36:   required from here
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const long long unsigned int’ and ‘long int’ [-Werror=sign-compare]
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = long long unsigned int; T = long long int]’:
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:405:3:   required from ‘void Poco::Dynamic::VarHolder::convertUnsignedToSigned(const F&, T&) const [with F = long long unsigned int; T = long long int]’
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:3475:36:   required from here
/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const long long unsigned int’ and ‘long long int’ [-Werror=sign-compare]
cc1plus: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/cossdk.dir/build.make:66: src/CMakeFiles/cossdk.dir/cos_api.cpp.o] Error 1
make[2]: Leaving directory '/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/build'
make[1]: *** [CMakeFiles/Makefile2:120: src/CMakeFiles/cossdk.dir/all] Error 2
make[1]: Leaving directory '/home/ubuntu/open_source/cos-cpp-sdk-v5-5.5.4/build'
make: *** [Makefile:87: all] Error 2

**Comment by chen-honggang** [comment]
第三方Poco库在你的编译环境重新编译一下即可
