### ISSUE TITLE
 error: implicitly-declared ‘qcloud_cos::LoggingEnabled::LoggingEnabled(const qcloud_cos::LoggingEnabled&)’ is deprecated [-Werror=deprecated-copy]

### ISSUE THREAD

**Issue by xiaoxiong713** [tencentyun/cos-cpp-sdk-v5#110]
ake
/usr/bin/cmake -S/root/cos-cpp-sdk-v5-5.5.5 -B/root/cos-cpp-sdk-v5-5.5.5/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /root/cos-cpp-sdk-v5-5.5.5/build/CMakeFiles /root/cos-cpp-sdk-v5-5.5.5/build//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/root/cos-cpp-sdk-v5-5.5.5/build'
make  -f src/CMakeFiles/cossdk.dir/build.make src/CMakeFiles/cossdk.dir/depend
make[2]: Entering directory '/root/cos-cpp-sdk-v5-5.5.5/build'
cd /root/cos-cpp-sdk-v5-5.5.5/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /root/cos-cpp-sdk-v5-5.5.5 /root/cos-cpp-sdk-v5-5.5.5/src /root/cos-cpp-sdk-v5-5.5.5/build /root/cos-cpp-sdk-v5-5.5.5/build/src /root/cos-cpp-sdk-v5-5.5.5/build/src/CMakeFiles/cossdk.dir/DependInfo.cmake --color=
Consolidate compiler generated dependencies of target cossdk
make[2]: Leaving directory '/root/cos-cpp-sdk-v5-5.5.5/build'
make  -f src/CMakeFiles/cossdk.dir/build.make src/CMakeFiles/cossdk.dir/build
make[2]: Entering directory '/root/cos-cpp-sdk-v5-5.5.5/build'
[  2%] Building CXX object src/CMakeFiles/cossdk.dir/cos_api.cpp.o
cd /root/cos-cpp-sdk-v5-5.5.5/build/src && /usr/bin/c++  -I/root/cos-cpp-sdk-v5-5.5.5/include -I/root/cos-cpp-sdk-v5-5.5.5/third_party/include -std=c++11 -Werror -Wall -Wextra -MD -MT src/CMakeFiles/cossdk.dir/cos_api.cpp.o -MF CMakeFiles/cossdk.dir/cos_api.cpp.o.d -o CMakeFiles/cossdk.dir/cos_api.cpp.o -c /root/cos-cpp-sdk-v5-5.5.5/src/cos_api.cpp
In file included from /root/cos-cpp-sdk-v5-5.5.5/include/op/bucket_op.h:16,
                 from /root/cos-cpp-sdk-v5-5.5.5/include/cos_api.h:4,
                 from /root/cos-cpp-sdk-v5-5.5.5/src/cos_api.cpp:1:
/root/cos-cpp-sdk-v5-5.5.5/include/response/bucket_resp.h: In member function ‘qcloud_cos::LoggingEnabled qcloud_cos::GetBucketLoggingResp::GetLoggingEnabled() const’:
/root/cos-cpp-sdk-v5-5.5.5/include/response/bucket_resp.h:343:53: error: implicitly-declared ‘qcloud_cos::LoggingEnabled::LoggingEnabled(const qcloud_cos::LoggingEnabled&)’ is deprecated [-Werror=deprecated-copy]
  343 |   LoggingEnabled GetLoggingEnabled() const { return m_rules; }
      |                                                     ^~~~~~~
In file included from /root/cos-cpp-sdk-v5-5.5.5/include/cos_sys_config.h:5,
                 from /root/cos-cpp-sdk-v5-5.5.5/include/op/bucket_op.h:10,
                 from /root/cos-cpp-sdk-v5-5.5.5/include/cos_api.h:4,
                 from /root/cos-cpp-sdk-v5-5.5.5/src/cos_api.cpp:1:
/root/cos-cpp-sdk-v5-5.5.5/include/cos_defines.h:516:19: note: because ‘qcloud_cos::LoggingEnabled’ has user-provided ‘qcloud_cos::LoggingEnabled& qcloud_cos::LoggingEnabled::operator=(const qcloud_cos::LoggingEnabled&)’
  516 |   LoggingEnabled& operator=(const LoggingEnabled& obj) {
      |                   ^~~~~~~~
In file included from /root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/Var.h:24,
                 from /root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/JSON/Array.h:23,
                 from /root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/JSON/Object.h:22,
                 from /root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/JSON/ParserImpl.h:22,
                 from /root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/JSON/Parser.h:22,
                 from /root/cos-cpp-sdk-v5-5.5.5/include/cos_config.h:10,
                 from /root/cos-cpp-sdk-v5-5.5.5/include/op/base_op.h:9,
                 from /root/cos-cpp-sdk-v5-5.5.5/include/op/bucket_op.h:11,
                 from /root/cos-cpp-sdk-v5-5.5.5/include/cos_api.h:4,
                 from /root/cos-cpp-sdk-v5-5.5.5/src/cos_api.cpp:1:
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = signed char; T = unsigned int]’:
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:370:23:   required from ‘void Poco::Dynamic::VarHolder::convertSignedToUnsigned(const F&, T&) const [with F = signed char; T = unsigned int]’
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:771:36:   required from here
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const signed cha’ and ‘unsigned int’ [-Werror=sign-compare]
  419 |   if (from > std::numeric_limits<T>::max())
      |       ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = signed char; T = long unsigned int]’:
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:370:23:   required from ‘void Poco::Dynamic::VarHolder::convertSignedToUnsigned(const F&, T&) const [with F = signed char; T = long unsigned int]’
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:776:36:   required from here
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const signed cha’ and ‘long unsigned int’ [-Werror=sign-compare]
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = signed char; T = long long unsigned int]’:
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:370:23:   required from ‘void Poco::Dynamic::VarHolder::convertSignedToUnsigned(const F&, T&) const [with F = signed char; T = long long unsigned int]’
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:788:36:   required from here
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const signed cha’ and ‘long long unsigned int’ [-Werror=sign-compare]
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = short int; T = unsigned int]’:
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:370:23:   required from ‘void Poco::Dynamic::VarHolder::convertSignedToUnsigned(const F&, T&) const [with F = short int; T = unsigned int]’
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:927:36:   required from here
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const short int’ and ‘unsigned int’ [-Werror=sign-compare]
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = short int; T = long unsigned int]’:
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:370:23:   required from ‘void Poco::Dynamic::VarHolder::convertSignedToUnsigned(const F&, T&) const [with F = short int; T = long unsigned int]’
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:932:36:   required from here
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const short int’ and ‘long unsigned int’ [-Werror=sign-compare]
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = short int; T = long long unsigned int]’:
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:370:23:   required from ‘void Poco::Dynamic::VarHolder::convertSignedToUnsigned(const F&, T&) const [with F = short int; T = long long unsigned int]’
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:944:36:   required from here
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const short int’ and ‘long long unsigned int’ [-Werror=sign-compare]
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = int; T = unsigned int]’:
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:370:23:   required from ‘void Poco::Dynamic::VarHolder::convertSignedToUnsigned(const F&, T&) const [with F = int; T = unsigned int]’
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:1081:36:   required from here
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const int’ and ‘unsigned int’ [-Werror=sign-compare]
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = int; T = long unsigned int]’:
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:370:23:   required from ‘void Poco::Dynamic::VarHolder::convertSignedToUnsigned(const F&, T&) const [with F = int; T = long unsigned int]’
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:1086:36:   required from here
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const int’ and ‘long unsigned int’ [-Werror=sign-compare]
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = int; T = long long unsigned int]’:
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:370:23:   required from ‘void Poco::Dynamic::VarHolder::convertSignedToUnsigned(const F&, T&) const [with F = int; T = long long unsigned int]’
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:1098:36:   required from here
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const int’ and ‘long long unsigned int’ [-Werror=sign-compare]
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = long int; T = long unsigned int]’:
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:370:23:   required from ‘void Poco::Dynamic::VarHolder::convertSignedToUnsigned(const F&, T&) const [with F = long int; T = long unsigned int]’
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:1238:36:   required from here
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const long int’ and ‘long unsigned int’ [-Werror=sign-compare]
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = long int; T = long long unsigned int]’:
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:370:23:   required from ‘void Poco::Dynamic::VarHolder::convertSignedToUnsigned(const F&, T&) const [with F = long int; T = long long unsigned int]’
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:1250:36:   required from here
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const long int’ and ‘long long unsigned int’ [-Werror=sign-compare]
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = long long int; T = long unsigned int]’:
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:370:23:   required from ‘void Poco::Dynamic::VarHolder::convertSignedToUnsigned(const F&, T&) const [with F = long long int; T = long unsigned int]’
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:3322:36:   required from here
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const long long int’ and ‘long unsigned int’ [-Werror=sign-compare]
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = long long int; T = long long unsigned int]’:
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:370:23:   required from ‘void Poco::Dynamic::VarHolder::convertSignedToUnsigned(const F&, T&) const [with F = long long int; T = long long unsigned int]’
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:3332:36:   required from here
/root/cos-cpp-sdk-v5-5.5.5/third_party/include/Poco/Dynamic/VarHolder.h:419:12: error: comparison of integer expressions of different signedness: ‘const long long int’ and ‘long long unsigned int’ [-Werror=sign-compare]
cc1plus: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/cossdk.dir/build.make:79: src/CMakeFiles/cossdk.dir/cos_api.cpp.o] Error 1
make[2]: Leaving directory '/root/cos-cpp-sdk-v5-5.5.5/build'
make[1]: *** [CMakeFiles/Makefile2:121: src/CMakeFiles/cossdk.dir/all] Error 2
make[1]: Leaving directory '/root/cos-cpp-sdk-v5-5.5.5/build'
make: *** [Makefile:94: all] Error 2

**Comment by chen-honggang** [comment]
Poco库建议自己重新编译一下，代码库自带和你的编译环境可能不一致
