### ISSUE TITLE
Mac compile issue: need to modify CMAKE_CXX_FLAGS parameter

### ISSUE THREAD

**Issue by kodywu-github** [tencentyun/cos-cpp-sdk-v5#112]
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -Wall -Wextra -Wno-parentheses-equality -Wsign-compare -Wdeprecated-copy -Wunused-private-field")

**Comment by Huberyxiao** [comment]
Building Arm64 Apple Silicon is now supported
