### ISSUE TITLE
经常出现上传超时的错误,和网速没关系,因为使用你们自带的测试工具可以正常上传

### ISSUE THREAD

**Issue by FourTest** [tencentyun/cos-cpp-sdk-v5#113]
经常出现上传超时的错误,和网速没关系,因为使用你们自带的测试工具可以正常上传
下面是打印的出错信息,GetErrorMsg返回了一个超时的错误,HttpStatus返回-1

HttpStatus:-1
GetErrorCode:  
GetErrorMsg:TimeoutException:Timeout  
GetResourceAddr:  
GetXCosRequestId:  
GetXCosTraceId:  
Tag:

我也联系过售后,他查了服务器那边日志,说是传的太慢,然后被服务器踢掉了

**Comment by Huberyxiao** [comment]
这种客户端、中间网络链路、服务端抖动，都是有可能导致连接超时的。具体情况还是得客户端的情况
