### ISSUE TITLE
这个sdk可真烂！水平太次

### ISSUE THREAD

**Issue by gotomypc** [tencentyun/cos-cpp-sdk-v5#123]
搞不懂还使用什么poco，婆娘的裹脚一般，如果不是使用你们腾讯云，懒得采纳。一堆的bug，还得自己修复。

**Comment by gotomypc** [comment]
仅仅看这个makefile，就知道这个水准不是一般的水！

**Comment by gotomypc** [comment]
经过折腾，一堆的依赖和编译配置，这个lib的水准，可谓是地球之最，算了，拜拜了，不用你们的。
浪费时间可耻，用这个lib，着实是浪费宝贵的时间！！！

**Comment by gotomypc** [comment]
建议后面的兄弟，如果不得已用tencent cos c++编写，可采用grpc调用别的进程方式解决，省的在这个lib上浪费时间。

**Comment by Waitforomething2023** [comment]
poco一堆隐性bug，真是大粪，受不了了。真的

**Comment by Huberyxiao** [comment]
有需求可以通过腾讯云售后进行联系

**Comment by hehechen** [comment]
> 建议后面的兄弟，如果不得已用tencent cos c++编写，可采用grpc调用别的进程方式解决，省的在这个lib上浪费时间。

@gotomypc 用 aws s3 sdk 访问腾讯云的 cos 可行不？

**Comment by CvRain** [comment]
> > 建议后面的兄弟，如果不得已用tencent cos c++编写，可采用grpc调用别的进程方式解决，省的在这个lib上浪费时间。
> 
> [@gotomypc](https://github.com/gotomypc) 用 aws s3 sdk 访问腾讯云的 cos 可行不？

可以使用的，我已经在项目里使用aws-sdk-cpp s3了，对象存储的基本api都是通用的。腾讯云就是一坨屎啊。
