### ISSUE TITLE
关于长连接的问题

### ISSUE THREAD

**Issue by 1261385937** [tencentyun/cos-cpp-sdk-v5#159]
sdk貌似不支持 keepalive
然后我修改sdk源码后，强行在header中加入 Connection - keepalive
一次http 请求后，服务端 无视keepalive，依然关闭连接。

1、http协议的 keepalive 怎么设置，才能有效？因为我需要对 大量的key进行读取数据
2、请问有基于tcp协议的sdk吗？
3、假如一个key的数据很大，我看现在的处理是 写到文件，能设置回调分段处理吗（我拿到一部分就转发走）

**Comment by 1261385937** [comment]
@huberyxxiao

**Comment by Huberyxiao** [comment]
1、当前 cpp sdk 不支持长链接
2、目前没有，我们服务端 的 api也是 http 协议的
3、目前不支持这样操作
如果需要的话，建议自行封装一下api，sdk 的本质就是对 api 接口的封装

**Comment by 1261385937** [comment]
@Huberyxiao 用了aws的sdk了

**Comment by dongxiao1198** [comment]
@1261385937 你切aws sdk后用着没问题吧？我也想放弃他们这个sdk了毛病太多了

**Comment by 1261385937** [comment]
> [@1261385937](https://github.com/1261385937) 你切aws sdk后用着没问题吧？我也想放弃他们这个sdk了毛病太多了

没问题，兼容的
