### ISSUE TITLE
Valgrind 报：Mismatched free() / delete / delete []错误

### ISSUE THREAD

**Issue by syzby** [tencentyun/cos-cpp-sdk-v5#33]
CosResult::ParseFromHttpResponse里面的cstr要用delete []释放，否则会报错，日志如下：

==21956== Mismatched free() / delete / delete []
==21956==    at 0x4C2B40D: operator delete(void*) (vg_replace_malloc.c:586)
==21956==    by 0x64FAC2: qcloud_cos::CosResult::ParseFromHttpResponse(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, std::string const&) (in /root/projects/luckin/mp/cmake_build/mp)
==21956==    by 0x66AE65: qcloud_cos::BaseOp::NormalAction(std::string const&, std::string const&, qcloud_cos::BaseReq const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, std::string const&, bool, qcloud_cos::BaseResp*) (in /root/projects/luckin/mp/cmake_build/mp)
==21956==    by 0x66A8C8: qcloud_cos::BaseOp::NormalAction(std::string const&, std::string const&, qcloud_cos::BaseReq const&, std::string const&, bool, qcloud_cos::BaseResp*) (in /root/projects/luckin/mp/cmake_build/mp)
==21956==    by 0x638896: qcloud_cos::ObjectOp::HeadObject(qcloud_cos::HeadObjectReq const&, qcloud_cos::HeadObjectResp*) (in /root/projects/luckin/mp/cmake_build/mp)
==21956==    by 0x63870F: qcloud_cos::ObjectOp::IsObjectExist(std::string const&, std::string const&) (in /root/projects/luckin/mp/cmake_build/mp)
==21956==    by 0x60129A: qcloud_cos::CosAPI::IsObjectExist(std::string const&, std::string const&) (in /root/projects/luckin/mp/cmake_build/mp)

**Comment by Huberyxiao** [comment]
该问题已修复
