### ISSUE TITLE
为何要这么多依赖

### ISSUE THREAD

**Issue by DyncEric** [tencentyun/cos-cpp-sdk-v5#48]
阿里云OSS的SDK下载下来编译就能用。腾讯为何要搞这么多依赖库

**Comment by DyncEric** [comment]
这些库完全可以打包到工程里面，这样可以有效提高开发效率。

**Comment by Huberyxiao** [comment]
目前仅依赖poco和openssl。已提供部分平台动态库，如需其他版本可自行编译依赖库
