### ISSUE TITLE
新手开发的?

### ISSUE THREAD

**Issue by app910** [tencentyun/cos-cpp-sdk-v5#49]
不提供二进制?
SDK不是提供方便的吗?大家的时间不是时间?1000个人使用,每个人浪费5个小时,也浪费了5000小时.
太多依赖,折腾下来要半天.

**Comment by JaosonMa** [comment]
同感 ，为什么不封装好 一个 SDK给大家 ， 这么大个公司，放出来个这玩意，这拿得出手吗

**Comment by app910** [comment]
已经提供编译好的了
