### ISSUE TITLE
【bug】MultiThreadDownload下载接口，打开本地文件失败会返回Succ

### ISSUE THREAD

**Issue by evan-xia** [tencentyun/cos-cpp-sdk-v5#66]
result:
 IsSucc:1
 GetHttpStatus:200
 GetErrorInfo:open file(./123/123) fail, errno=20
 GetErrorCode:
 GetErrorMsg:
 DebugString:IsSucc=true

代码这里状态设置上有些问题：  

![image](https://user-images.githubusercontent.com/10475867/118068916-c6d22980-b3d5-11eb-8187-465e1ce1976f.png)

**Comment by Huberyxiao** [comment]
问题已修复
