### ISSUE TITLE
不能在dll中使用

### ISSUE THREAD

**Issue by app910** [tencentyun/cos-cpp-sdk-v5#79]
不能在dll中使用,只要引用了qcloud_cos::CosAPI就会挂掉,即使不调用也会挂掉,dllmain都进不去
是不是你们一堆全局变量/静态变量哟

**Comment by app910** [comment]
话说你们没测试的吗?

**Comment by Huberyxiao** [comment]
当前已不再提供和维护sdk的库文件，均需要重新编译。有问题可以通过腾讯云客服联系我们
