### ISSUE TITLE
third_party目录下的Poco依赖的so固定了版本？

### ISSUE THREAD

**Issue by aLittleFat** [tencentyun/cos-cpp-sdk-v5#87]
third_party目录下的Poco库，ldd出来发现依赖的libssl和libcrypto依赖了固定的版本
libssl.so.10 => not found
libcrypto.so.10 => not found

**Comment by qqsunkist** [comment]
相同问题

**Comment by Huberyxiao** [comment]
可以重新基于源码编译第三方库
