### ISSUE TITLE
how can i make in MacOS arm64( apple m1)

### ISSUE THREAD

**Issue by nachoyang** [tencentyun/cos-cpp-sdk-v5#98]
"typeinfo for Poco::JSON::Array", referenced from:
      Poco::Dynamic::VarHolderImpl<Poco::JSON::Array>::type() const in cos_demo.cpp.o
  "typeinfo for Poco::Task", referenced from:
      typeinfo for qcloud_cos::AsyncTask in libcossdk.a(cos_api.cpp.o)
  "typeinfo for Poco::Dynamic::VarHolder", referenced from:
      typeinfo for Poco::Dynamic::VarHolderImpl<int> in cos_demo.cpp.o
      typeinfo for Poco::Dynamic::VarHolderImpl<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > in cos_demo.cpp.o
      typeinfo for Poco::Dynamic::VarHolderImpl<Poco::SharedPtr<Poco::JSON::Object, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::JSON::Object> > > in cos_demo.cpp.o
      typeinfo for Poco::Dynamic::VarHolderImpl<Poco::JSON::Array> in cos_demo.cpp.o
      typeinfo for Poco::Dynamic::VarHolderImpl<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > in libcossdk.a(object_op.cpp.o)
      typeinfo for Poco::Dynamic::VarHolderImpl<Poco::SharedPtr<Poco::JSON::Object, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::JSON::Object> > > in libcossdk.a(object_op.cpp.o)
  "typeinfo for Poco::Runnable", referenced from:
      typeinfo for qcloud_cos::FileCopyTask in libcossdk.a(file_copy_task.cpp.o)
      typeinfo for qcloud_cos::FileDownTask in libcossdk.a(file_download_task.cpp.o)
      typeinfo for qcloud_cos::FileUploadTask in libcossdk.a(file_upload_task.cpp.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/cos-demo] Error 1
make[1]: *** [demo/CMakeFiles/cos-demo.dir/all] Error 2
make: *** [all] Error 2

**Comment by Huberyxiao** [comment]
使用poco1.12.0版本重新编译，替换掉头文件和库文件即可
